output_root: '../'
pytorch_data_dir: '/datadrive/pytorch-data/'
experiment_name: "cocostuff"
res: 320
batch_size: 8
num_workers: 24
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
